apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: av75101jw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: av75101jw-nodejs 
  name: av75101jw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: av75101jw-nodejs 
